[package]
name = "numeric-algs"
version = "0.2.1"
authors = ["Bartłomiej Kamiński <fizyk20@gmail.com>"]
description = "Crate implementing some numerical algorithms"
license = "MIT"
repository = "https://github.com/fizyk20/numeric-algs.git"

[lib]
name = "numeric_algs"

[dependencies]
